### ISSUE TITLE
Declarative configuration

### ISSUE THREAD

**Issue by singulared** [hit-box/hitbox#36]
The main idea of this task is to add some mechanism that implements the ability to declaratively describe the hitbox configuration.
- HTTP server configuration (host, port, etc.)
- Backend configuration (ideally we can use multiple backends at the same time for some `endpoint` aka L1, L2 caches)

Main configuration entities:
- Endpoint (Some atomic cache configuration block identified by HTTP path, method or something else)
- Upstream (Application or multiple application instances that we want to wrap with a cache)
- Group (Group of `Endpoints` with the same configuration) (I think groups don't need in MVP)

Configuration manager should own configuration state and should have the ability to reload it on runtime. 

Basic example of config file (discussable)
```yaml
inbound:
  proto: HTTP
  port: 8080
  host: 0.0.0.0

upstreams:
  google:
    host: 8.8.8.8
    port: 8080

endpoints:
  matrics:
    matchers:
      - matcher:
          path: "/index/"
      - matcher:
          method: GET
```

**Comment by AndreyErmilov** [comment]
https://api.github.com/repos/vmg/redcarpet/issues?state=closed
```yaml
inbound:
  proto: HTTP
  port: 8080
  host: 0.0.0.0

backends:
  - redis:
      proto: redis
      host: 127.0.0.1
      port: 6379
      database: 0

upstreams:
  google:
    host: 8.8.8.8
    port: 8080
    endpoints:
      index:
        backends:
          - redis
        matchers:
          - matcher:
              path: "/index/"
          - matcher:
              method: GET
  github:
    host: api.github.com
    port: 80
    endpoints:
      issues:
        backends:
          - redis
        matchers:
          - matcher:
              path: "/repos/{user:string}/{repo:string}/issues/"
              method: GET
        keys:
          query:
            - type: enum
              name: state
              values:
                - closed
                - open
```

**Comment by AndreyErmilov** [comment]
It seems that we need to separate two layers from each other. The first layer is the structures which are the internal representation of the hitbox-server settings. The second layer is the user configuration (yaml etc.). The layer with the user configuration is converted into the first layer, the internal representation of the settings.
Both the first and second layers solve the same task, but each layer has its own specifics.
1. First of all, we don't want to use the internal structures of the hitbox server because we don't want to know about them. And we don't want to change everything if we need to change the internal structures of the hitbox server.
2. The second reason is that user configuration should be as simple as possible. We add groups, etc. to automate and reduce copying.

**Comment by AndreyErmilov** [comment]
TBD:
@singulared 
```yaml
# hitbox server base settings
server:
  host: 127.0.0.1
  port: 8080
  proto: HTTP

upstreams:
  default:
    host: 127.0.0.1
    port: 8080
    proto: HTTP

backends:
  default:
    proto: redis
    host: 127.0.0.1
    port: 6379
    database: 0

# map of cache policies
policies:
  default:
    cache: enabled
    lock: local
    stale: disabled
  non_cacheable:
    cache: disabled

# base settings
settings:
  default:
    prefix: my_app
    version: 1
    ttl: 30min
  short:
    ttl: 1min

# map of groups
groups:
  default:
    # there is no need to add this, because the defaults will apply by default
    policy: default
    settings: default
    backend: default
    upstream: default
  exclude:
    policy: non_cacheable

# list of all endpoint
endpoints:
  specific:
    - name: healthcheck
      path: "/healthcheck/"
      group: exclude
    - name: comments_by_cluster
      path: "/clusters/{cluster_id:i32}/comments/"
    # we can override specific parameter like settings with other settings from default group
    - name: cluster
      path: "/cluster/{cluster_id:i32}/"
      group: default
      settings: short
  default:
    group: default

```
